In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
import pandas as pd

In [20]:
# Read in the training and test datasets from previously created csv files
imdb_train = pd.read_csv('csv/imdb_train.csv')

In [21]:
corpus = imdb_train['text'].values

In [22]:
vectorizer = CountVectorizer()            # unigram

In [23]:
X = vectorizer.fit_transform(corpus)

In [24]:
print(vectorizer.get_feature_names()[0:5])

['00', '000', '0000000000001', '00001', '00015']


In [25]:
print(X.toarray())  

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))   # bigram

In [27]:
X2 = vectorizer2.fit_transform(corpus)

In [28]:
print(vectorizer2.get_feature_names()[0:5])

['00 01', '00 after', '00 alison', '00 am', '00 and']


In [55]:
print(X2)

  (0, 1265949)	1
  (0, 660809)	1
  (0, 1387407)	1
  (0, 1365804)	1
  (0, 423187)	1
  (0, 1389964)	1
  (0, 1160277)	1
  (0, 1306476)	1
  (0, 372687)	1
  (0, 976827)	1
  (0, 859428)	1
  (0, 1289564)	1
  (0, 1125437)	1
  (0, 372688)	1
  (0, 1225754)	2
  (0, 1369336)	1
  (0, 1421414)	1
  (0, 1108765)	1
  (0, 624183)	2
  (0, 666246)	2
  (0, 924463)	1
  (0, 1042894)	1
  (0, 604217)	1
  (0, 666058)	1
  (0, 843661)	1
  :	:
  (24999, 66189)	1
  (24999, 665758)	1
  (24999, 502502)	1
  (24999, 1335804)	1
  (24999, 1411883)	1
  (24999, 454897)	1
  (24999, 897174)	1
  (24999, 880611)	1
  (24999, 1239408)	1
  (24999, 168237)	1
  (24999, 1152652)	1
  (24999, 498110)	1
  (24999, 1090390)	1
  (24999, 30904)	1
  (24999, 108310)	1
  (24999, 249499)	1
  (24999, 366734)	1
  (24999, 888806)	1
  (24999, 219273)	1
  (24999, 745995)	1
  (24999, 503432)	1
  (24999, 763726)	1
  (24999, 399503)	1
  (24999, 1041620)	1
  (24999, 1352438)	1


In [36]:
vectorizer3 = CountVectorizer(analyzer='word', ngram_range=(3, 3))    # trigram

In [31]:
X3 = vectorizer3.fit_transform(corpus)

In [32]:
print(vectorizer3.get_feature_names()[0:5])

['00 01 percent', '00 after cohn', '00 alison agrees', '00 am and', '00 am once']


In [56]:
print(X3)

  (0, 3152314)	1
  (0, 1594521)	1
  (0, 3491037)	1
  (0, 3419433)	1
  (0, 978757)	1
  (0, 3497556)	1
  (0, 2771580)	1
  (0, 3291234)	1
  (0, 872855)	1
  (0, 2389860)	1
  (0, 2077599)	1
  (0, 3246569)	1
  (0, 2696606)	1
  (0, 872856)	1
  (0, 2923646)	1
  (0, 3438174)	1
  (0, 3593260)	1
  (0, 2663948)	1
  (0, 1478419)	2
  (0, 1624151)	1
  (0, 2285027)	1
  (0, 2517595)	1
  (0, 1429272)	1
  (0, 1621832)	1
  (0, 2036085)	1
  :	:
  (24999, 568863)	1
  (24999, 42127)	1
  (24999, 2296469)	1
  (24999, 1811356)	1
  (24999, 1038078)	1
  (24999, 3561190)	1
  (24999, 1172169)	1
  (24999, 850986)	1
  (24999, 2758597)	1
  (24999, 1620424)	1
  (24999, 1852801)	1
  (24999, 1366217)	1
  (24999, 3029973)	1
  (24999, 2359990)	1
  (24999, 926341)	1
  (24999, 1109568)	1
  (24999, 1334491)	1
  (24999, 2146708)	1
  (24999, 2515136)	1
  (24999, 1402565)	1
  (24999, 313562)	1
  (24999, 1163431)	1
  (24999, 3350257)	1
  (24999, 883326)	1
  (24999, 3389548)	1


In [38]:
import nltk
#nltk.download()
from nltk.corpus import stopwords
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [39]:
vectorizer4 = CountVectorizer(analyzer='word', ngram_range=(3, 3), stop_words= stopwords.words('english'))    # trigram with stop_words

In [40]:
X4 = vectorizer4.fit_transform(corpus)

In [41]:
print(vectorizer4.get_feature_names()[0:5])

['00 01 percent', '00 90 minutes', '00 air horror', '00 alison agrees', '00 back would']


In [42]:
print(X4)

  (0, 783298)	1
  (0, 2322131)	1
  (0, 2540973)	1
  (0, 656689)	1
  (0, 1909309)	1
  (0, 2259740)	1
  (0, 656695)	1
  (0, 2739226)	1
  (0, 2223555)	1
  (0, 2057178)	1
  (0, 1170652)	1
  (0, 1682416)	1
  (0, 1994423)	1
  (0, 979505)	1
  (0, 817916)	1
  (0, 2654367)	1
  (0, 718930)	1
  (0, 2223890)	1
  (0, 2238611)	1
  (0, 1772724)	1
  (0, 2540965)	1
  (0, 606305)	1
  (0, 716720)	1
  (0, 1772933)	1
  (0, 2685441)	1
  :	:
  (24999, 401192)	1
  (24999, 410446)	1
  (24999, 644788)	1
  (24999, 261028)	1
  (24999, 1732311)	1
  (24999, 976881)	1
  (24999, 34527)	1
  (24999, 1796412)	1
  (24999, 1431268)	1
  (24999, 851931)	1
  (24999, 978530)	1
  (24999, 2307378)	1
  (24999, 1486108)	1
  (24999, 1135909)	1
  (24999, 2374112)	1
  (24999, 1874044)	1
  (24999, 718317)	1
  (24999, 1747342)	1
  (24999, 1120049)	1
  (24999, 2054064)	1
  (24999, 876960)	1
  (24999, 2006269)	1
  (24999, 1144315)	1
  (24999, 969589)	1
  (24999, 2600919)	1


In [57]:
print(X4)

  (0, 35204)	1
  (0, 62842)	1
  (0, 65735)	1
  (0, 92231)	1
  (0, 97109)	1
  (0, 99046)	1
  (0, 129025)	1
  (0, 151570)	1
  (0, 199066)	1
  (0, 208608)	1
  (0, 227919)	1
  (0, 273416)	1
  (0, 273419)	1
  (0, 350502)	1
  (0, 360164)	1
  (0, 382313)	1
  (0, 389488)	1
  (0, 402723)	1
  (0, 466257)	1
  (0, 492004)	1
  (0, 502290)	1
  (0, 525878)	1
  (0, 526053)	1
  (0, 532714)	1
  (0, 561635)	1
  :	:
  (24999, 644788)	1
  (24999, 718317)	1
  (24999, 851931)	1
  (24999, 876960)	1
  (24999, 969589)	1
  (24999, 976881)	1
  (24999, 978530)	1
  (24999, 1120049)	1
  (24999, 1135909)	1
  (24999, 1144315)	1
  (24999, 1431268)	1
  (24999, 1486108)	1
  (24999, 1732311)	1
  (24999, 1747342)	1
  (24999, 1763624)	1
  (24999, 1796412)	1
  (24999, 1874044)	1
  (24999, 2006269)	1
  (24999, 2054064)	1
  (24999, 2182999)	1
  (24999, 2307378)	1
  (24999, 2374112)	1
  (24999, 2600919)	1
  (24999, 2670261)	1
  (24999, 2758618)	1


In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer   # you can do this at the outset -- but needed now...

In [46]:
ug_tf_idf = TfidfVectorizer(stop_words=stopwords.words('english'), ngram_range=(3,3))

In [47]:
X5 = ug_tf_idf.fit_transform(corpus)

In [48]:
print(X5)

  (0, 1741940)	0.08129927087991069
  (0, 1958870)	0.08129927087991069
  (0, 2682517)	0.08129927087991069
  (0, 2772095)	0.08129927087991069
  (0, 1002849)	0.08129927087991069
  (0, 35204)	0.08129927087991069
  (0, 895452)	0.08129927087991069
  (0, 2228549)	0.08129927087991069
  (0, 2159505)	0.08129927087991069
  (0, 701418)	0.08129927087991069
  (0, 1776991)	0.08129927087991069
  (0, 1800954)	0.08129927087991069
  (0, 2571860)	0.08129927087991069
  (0, 2229892)	0.08129927087991069
  (0, 1481690)	0.08129927087991069
  (0, 65735)	0.08129927087991069
  (0, 1350596)	0.08129927087991069
  (0, 2176390)	0.08129927087991069
  (0, 917496)	0.08129927087991069
  (0, 502290)	0.08129927087991069
  (0, 62842)	0.08129927087991069
  (0, 1493665)	0.08129927087991069
  (0, 2176083)	0.08129927087991069
  (0, 466257)	0.08129927087991069
  (0, 1741936)	0.08129927087991069
  :	:
  (24999, 1747342)	0.1775432248546652
  (24999, 718317)	0.1775432248546652
  (24999, 1874044)	0.1775432248546652
  (24999, 2374112

In [49]:
# you can also use a TfidfTransform with a unigram or bigram or n-gram in general
from sklearn.feature_extraction.text import TfidfTransformer
tfidf2 = TfidfTransformer()

In [50]:
# here we use the TfidfTransform on the trigram result from before
tfidf2.fit(X4)

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)

In [51]:
X6 = tfidf2.transform(X4)

In [52]:
print(repr(X6))

<25000x2803249 sparse matrix of type '<class 'numpy.float64'>'
	with 2946853 stored elements in Compressed Sparse Row format>


In [53]:
print(X6)

  (0, 2772095)	0.08129927087991069
  (0, 2769735)	0.08129927087991069
  (0, 2739226)	0.08129927087991069
  (0, 2708505)	0.08129927087991069
  (0, 2693001)	0.08129927087991069
  (0, 2685441)	0.08129927087991069
  (0, 2682517)	0.08129927087991069
  (0, 2654367)	0.08129927087991069
  (0, 2644842)	0.08129927087991069
  (0, 2632641)	0.08129927087991069
  (0, 2604753)	0.08129927087991069
  (0, 2576342)	0.08129927087991069
  (0, 2571860)	0.08129927087991069
  (0, 2540973)	0.08129927087991069
  (0, 2540965)	0.08129927087991069
  (0, 2465946)	0.08129927087991069
  (0, 2454163)	0.08129927087991069
  (0, 2445037)	0.08129927087991069
  (0, 2444908)	0.08129927087991069
  (0, 2438320)	0.08129927087991069
  (0, 2387847)	0.08129927087991069
  (0, 2384345)	0.08129927087991069
  (0, 2365976)	0.08129927087991069
  (0, 2322131)	0.08129927087991069
  (0, 2303644)	0.08129927087991069
  :	:
  (24999, 2006269)	0.17754322485466517
  (24999, 1874044)	0.17754322485466517
  (24999, 1796412)	0.17754322485466517
  